version: 0.1

# This is a configuration file for AWS CodeBuild.  It just runs maven.
phases:
  build:
    commands:
      - echo Testing started on `date`
      - mvn test
      - echo Testing finished on `date`
  post_build:
    commands:
      - echo Build started on `date`
      - mvn package
      - echo Build finished on `date`
artifacts:
  files:
    - target/spring-cloud-aws-environment-demo-1.war
  discard-paths: yes
