version: 0.2

# This is a configuration file for AWS CodeBuild.  It just runs mvn package without tests.
# The test phase is run separately by CodePipeline to enable faster builds.
# The output file is identified by its name only (getting rid of 'target' on the path), which means it will 
# show up later in the S3 bucket with just its name and no pathing.
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn package -DskipTests
      - echo Build finished on `date`
artifacts:
  files:
    - target/spring-cloud-aws-environment-demo-1.war
  discard-paths: yes
