version: 0.2

# This is a configuration file for AWS CodeBuild.  It just runs maven.           
# The test phase is run separately from the package phase, just to enable splitting later.  
# The output file is identified by its name only (getting rid of 'target' on the path), which means it will      
# show up later in the S3 bucket with just its name and no pathing. 
phases:
  install:
    runtime-versions:
      java: corretto17  # formerly openjdk11 
  build:
    commands:
      - echo Testing started on `date`
      - mvn -f pom-jar.xml test
      - echo Testing finished on `date`
  post_build:
    commands:
      - echo Build started on `date`
      - mvn -f pom-jar.xml package -DskipTests
      - echo Build finished on `date`
reports:
  # Maven surefire plugin runs JUnit test and writes to target/surefire-reports/*.xml
  mvn-test-reports:
    files:
    - "target/surefire-reports/*.xml"
    file-format: "JUNITXML"      
artifacts:
  files:
    - target/cloud-build-demo-17.jar
  discard-paths: yes
#  This is implementing a "local / custom" cache to reduce maven download time on subsequent builds.
#  See https://aws.amazon.com/about-aws/whats-new/2019/02/aws-codebuild-now-supports-local-caching/
cache:
  paths:
    - '/root/.m2/**/*'
